### ISSUE TITLE
Changing the path for previews?

### ISSUE THREAD

**Issue by closewall** [nextcloud/previewgenerator#391]
Would it be possible for the preview generator to send preview files/thumbnails to a different directory/docker mapping?

I would like to keep my Nextcloud Data and thumbnails in separate locations for performance reasons. I would much rather have my Nextcloud previews generated on an SSD rather than my HDD array, but I don't see any settings for changing the directory.

**Comment by pulsejet** [comment]
I don't think that's something this app can fix, the preview generation happens in the server itself. I use something like this to keep the previews on SSD and data on RAID.

```yaml
  app:
    ...
    volumes:
      - /faststorage/nextcloud:/var/www/html
      - /raidarray/ncdata:/var/www/html/data
      - /faststorage/nc_appdata_oc213fxr1cuh:/var/www/html/data/nc_appdata_oc213fxr1cuh
```
